config/routes.rb
Dz4::Application.routes.draw do
  get "main/index"

  get "main/about"

  get "main/help"

  get "main/contacts"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end

  def about
  end

  def help
  end

  def contacts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dz4</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/about.html.erb
<p><%= link_to "вернуться", main_index_path%></p>

<head>

   <title>визитка</title>

</head>
<body>



<img style="width: 350px; height: 263px;" src="http://www.novgorodauto.ru/walls/1152_864/bugatti_veyron_grand_sport_2009.jpg" align = "left">


<font size = "+6" color = "blue"><b>Жуков Станислав</b></font>
<p><font size = "+6" color = "blue"><b>[шк. 1543]</b></font></p>
<p> </p>
<p> </p>
<hr></hr>
<font size = "+2"><b>Контактная информация:</b></font>
<pre><div>Телефон  000
Email   blablabla@yandex.ru
Вк   blablabla</div></pre>
</body>

app/views/main/contacts.html.erb
<p><%= link_to "вернуться", main_index_path%></p>
<html>
         <head>
         <title>Monday begins on friday</title>
		 </head>
		     <body bgcolor = "ff9640">
			  <img src = "Cover1.jpg" align = "right" alt="нет картинки"></img>
			 <div align = "left">
<b><u>«Понедельник начинается в субботу» (1965) - </u></b>
             <blockquote>фантастическая юмористическая повесть братьев Стругацких, одно из наиболее своеобразных воплощений 
советской утопии 1960-х годов, художественная реализация мечты авторов о возможности для современного
 талантливого человека сосредоточиться на научном творчестве и познании тайн Вселенной. 
 Существенную роль в повести играют также ярко выраженные сатирические мотивы; 
 в ней высмеиваются приспособленцы, бюрократы и жулики от науки.</blockquote></div>
<p> <ul type = "square">
     <li><b>Жанр:</b>	повесть фантастика</li>
     <li><b>Автор:</b>	Братья Стругацкие</li>
	 <li><b>Язык оригинала:</b>	русский</li>
     <li><b>Год написания:</b>	1964—1965 гг.</li>	 
     <li><b>Публикация:</b>	1964</li>
     <li><b>Отдельное издание:</b>	1965</li>
     <li><b>Издательство:</b>	Детская литература</li>	 
</ul>	 </p>
             <font size = "+2"><b>Сюжет</b></font>
			 <hr size = "3" color = "grey"></hr>
			 <div align = "left">
<pre>   Повесть состоит из трёх частей: «Суета вокруг дивана», «Суета сует», «Всяческая суета». Первая часть композиционно работает как вводная, вторая носит сатирический 
и полемический характер,третья пытается исследовать природу научного творчества и роль, которую играет в нём воображение и способность к нестандартному мышлению.</pre></div>
             <img src = "2.jpg" align = "left" hspace = "30" alt="нет картинки"></img>
			 <div align = "left">
<pre>   В произведении действуют и упоминаются персонажи и предметы русских сказок, фольклорных и мифологических произведений; несмотря на это
 повествование носит скорее подчёркнуто бытовой, чем сказочный характер.</pre></div>
    <ol type = "I">
	     <li><font color = "94002d">Авгуры</font> — традиционно занимаются предсказаниями</li>
		  <li>Вурдалаки — согласно глоссарию, «Маги, вставшие по тем или иным причинам на путь абстрактного зла»</li>
		   <li>Василий, говорящий кот — «Кот учёный» из пролога поэмы Пушкина «Руслан и Людмила»</li>
		    <li>Гекатонхейры — сторукие пятидесятиголовые великаны, сыновья верховного бога Урана (неба) и Геи (земли): Бриарей, Котт и Гиес. В книге живут в
			виварии НИИЧАВО , иногда привлекаются для общих работ в качестве грузчиков</li>
			 <li>Гидра — согласно глоссарию, «реально существующая многоголовая рептилия, дочь З. Горыныча и плезиозаврихи из озера Лох-Несс.»</li>
			  <li>Говорящая щука — щука из русской народная сказки «По щучьему велению»</li>
			   <li>Голем — согласно глоссарию, «один из первых кибернетических роботов»</li>
			    <li>Гомункулус — «искусственное человекоподобное существо, используют для биомеханического моделирования.»</li>
				 <li>Гномы — согласно глоссарию, «большинство гномов — это забытые и сильно усохшие дубли»</li>
	</ol>
	</body>
	</html>

app/views/main/help.html.erb
<p><%= link_to "вернуться", main_index_path%></p>
<html>
    <head>
	  <title>Таблица</title>
	</head>
   <body>
       <table border = "1" cellspacing = "0">
	     <tr height = "20"><td width = "100"><font>blablabla<a href = "http://dnttm.ru">dnttm</a>blablabla</font></td><td width = "100" rowspan = "3"><img src = "http://www.gizmonews.ru/wp-content/uploads/2011/10/yandex.jpg" width = "100" height = "60"></td><td width = "25%">&nbsp;</td><td width = "100"rowspan = "3">&nbsp;</td></tr>
         <tr height = "20"><td width = "100">&nbsp;</td><td width = "100">&nbsp;</td></tr>
		 <tr height = "20"><td width = "100">&nbsp;</td><td width = "100" rowspan = "2">&nbsp;</td></tr>
		 <tr height = "20"><td width = "100">&nbsp;</td><td width = "100">&nbsp;</td><td width = "100">&nbsp;</td></tr>
		 <tr height = "20" bgcolor = "yellow"><td width = "100" colspan = "2"><font face = "Verdana" color = "red"><b>один</b><font><font face = "Verdana" color = "black"> два </font><font face = "Verdana" color = "red"><b>один</b></font></td><td width = "100">&nbsp;</td><td width = "100">&nbsp;</td></tr>
       </table>  
   </body>
 </html>  

app/views/main/index.html.erb
<html>
    <div><%= link_to "Домашнее задание 1", main_about_path%></div>
	<div><%= link_to "Домашнее задание 2", main_help_path%></div>
	<div><%= link_to "Домашнее задание 3", main_contacts_path%></div>
</html>